spring.application.name=MyIkea
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# Database configuration - LOCAL DEVELOPMENT
spring.datasource.url=jdbc:mysql://localhost:3306/myikea
spring.datasource.username=root
spring.datasource.password=Anubis@68
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
