spring.application.name=MyIkea
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://localhost:3306/myikea
spring.datasource.username=root
spring.datasource.password=Anubis@68
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver